import { MigrationInterface, QueryRunner } from "typeorm";

export class SetNumberPhone1705624416352 implements MigrationInterface {
    name = 'SetNumberPhone1705624416352'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "points_events" DROP CONSTRAINT "FK_points_event_events_sites"`);
        await queryRunner.query(`ALTER TABLE "event" DROP CONSTRAINT "FK_2671ad705325336d3ae1be4ea60"`);
        await queryRunner.query(`ALTER TABLE "points_events" DROP CONSTRAINT "FK_80b087bd8d6927fc9be6ba734bb"`);
        await queryRunner.query(`ALTER TABLE "events_points_site" DROP CONSTRAINT "FK_events_points_site_event_id"`);
        await queryRunner.query(`ALTER TABLE "events_points_site" DROP CONSTRAINT "FK_events_points_site_id_site"`);
        await queryRunner.query(`ALTER TABLE "site" DROP CONSTRAINT "FK_46ba93fc73b6e2d11638400c165"`);
        await queryRunner.query(`ALTER TABLE "site" DROP CONSTRAINT "FK_6a4f2c06ad82432494fc37fe6a5"`);
        await queryRunner.query(`ALTER TABLE "site" DROP CONSTRAINT "FK_ab02518d0430b2172bd88ac1e63"`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "create_at"`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "pointsEventsId"`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "event_repeats"`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "porcentual_value"`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "points"`);
        await queryRunner.query(`ALTER TABLE "events_points_site" DROP COLUMN "registration_date"`);
        await queryRunner.query(`ALTER TABLE "site" DROP CONSTRAINT "UQ_cfeaa7e14361e11b3fdfd9fc69f"`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "url"`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "createAt"`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "updateAt"`);
        await queryRunner.query(`ALTER TABLE "site" DROP CONSTRAINT "UQ_6a4f2c06ad82432494fc37fe6a5"`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "idPointValue"`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "pointsEventsId"`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "pointsMovementId"`);
        await queryRunner.query(`ALTER TABLE "points_events" ADD "name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "event" ADD "points" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "event" ADD "event_repeats" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "event" ADD "porcentual_value" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "event" ADD "create_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "event" ADD "pointsEventsId" integer`);
        await queryRunner.query(`ALTER TABLE "site" ADD "url" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "site" ADD CONSTRAINT "UQ_cfeaa7e14361e11b3fdfd9fc69f" UNIQUE ("url")`);
        await queryRunner.query(`ALTER TABLE "site" ADD "isActive" boolean DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "site" ADD "createAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "site" ADD "updateAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "site" ADD "idPointValue" integer`);
        await queryRunner.query(`ALTER TABLE "site" ADD CONSTRAINT "UQ_6a4f2c06ad82432494fc37fe6a5" UNIQUE ("idPointValue")`);
        await queryRunner.query(`ALTER TABLE "site" ADD "pointsEventsId" integer`);
        await queryRunner.query(`ALTER TABLE "site" ADD "pointsMovementId" integer`);
        await queryRunner.query(`ALTER TABLE "event" ADD "registration_state" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "events_points_site" ADD "registration_state" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "events_points_site" ADD "pointsEventsId" integer`);
        await queryRunner.query(`ALTER TABLE "user_admin_entity" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "user_admin_entity" ADD "phone" integer`);
        await queryRunner.query(`ALTER TABLE "points_events" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "points_events" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "event" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event" ALTER COLUMN "description" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event" DROP CONSTRAINT "UQ_b535fbe8ec6d832dde22065ebdb"`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "event" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event" DROP CONSTRAINT "UQ_d345d5fafe5dd3261d69a295068"`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "event" ADD "description" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "update_at"`);
        await queryRunner.query(`ALTER TABLE "event" ADD "update_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "points_events" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "points_events" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "points_events" ALTER COLUMN "eventIdEvent" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "points_events" ALTER COLUMN "siteIdSite" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "points_events" ALTER COLUMN "expiration_date" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "events_points_site" ALTER COLUMN "eventIdEvent" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events_points_site" ALTER COLUMN "siteIdSite" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events_points_site" ALTER COLUMN "expiration_date" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "site" DROP CONSTRAINT "UQ_9669a09fcc0eb6d2794a658f647"`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "site" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "site" ADD "description" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "points_events" ADD CONSTRAINT "FK_dc0a053b5d0fedf82cf38f248e7" FOREIGN KEY ("userId") REFERENCES "user_admin_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "points_events" ADD CONSTRAINT "FK_80b087bd8d6927fc9be6ba734bb" FOREIGN KEY ("siteIdSite") REFERENCES "site"("idSite") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "points_events" ADD CONSTRAINT "FK_bb345c1b75a0d8f1ac768345f27" FOREIGN KEY ("eventIdEvent") REFERENCES "event"("id_event") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event" ADD CONSTRAINT "FK_2671ad705325336d3ae1be4ea60" FOREIGN KEY ("pointsEventsId") REFERENCES "points_events"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "site" ADD CONSTRAINT "FK_6a4f2c06ad82432494fc37fe6a5" FOREIGN KEY ("idPointValue") REFERENCES "point_value"("id_point_value") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "site" ADD CONSTRAINT "FK_46ba93fc73b6e2d11638400c165" FOREIGN KEY ("pointsEventsId") REFERENCES "points_events"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "site" ADD CONSTRAINT "FK_ab02518d0430b2172bd88ac1e63" FOREIGN KEY ("pointsMovementId") REFERENCES "points_movement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events_points_site" ADD CONSTRAINT "FK_f41f3265acb011b6b51f17fa077" FOREIGN KEY ("pointsEventsId") REFERENCES "points_events"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "events_points_site" DROP CONSTRAINT "FK_f41f3265acb011b6b51f17fa077"`);
        await queryRunner.query(`ALTER TABLE "site" DROP CONSTRAINT "FK_ab02518d0430b2172bd88ac1e63"`);
        await queryRunner.query(`ALTER TABLE "site" DROP CONSTRAINT "FK_46ba93fc73b6e2d11638400c165"`);
        await queryRunner.query(`ALTER TABLE "site" DROP CONSTRAINT "FK_6a4f2c06ad82432494fc37fe6a5"`);
        await queryRunner.query(`ALTER TABLE "event" DROP CONSTRAINT "FK_2671ad705325336d3ae1be4ea60"`);
        await queryRunner.query(`ALTER TABLE "points_events" DROP CONSTRAINT "FK_bb345c1b75a0d8f1ac768345f27"`);
        await queryRunner.query(`ALTER TABLE "points_events" DROP CONSTRAINT "FK_80b087bd8d6927fc9be6ba734bb"`);
        await queryRunner.query(`ALTER TABLE "points_events" DROP CONSTRAINT "FK_dc0a053b5d0fedf82cf38f248e7"`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "site" ADD "description" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "site" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "site" ADD CONSTRAINT "UQ_9669a09fcc0eb6d2794a658f647" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "events_points_site" ALTER COLUMN "expiration_date" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "events_points_site" ALTER COLUMN "siteIdSite" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events_points_site" ALTER COLUMN "eventIdEvent" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "points_events" ALTER COLUMN "expiration_date" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "points_events" ALTER COLUMN "siteIdSite" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "points_events" ALTER COLUMN "eventIdEvent" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "points_events" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "points_events" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "update_at"`);
        await queryRunner.query(`ALTER TABLE "event" ADD "update_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "event" ADD "description" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "event" ADD CONSTRAINT "UQ_d345d5fafe5dd3261d69a295068" UNIQUE ("description")`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "event" ADD "name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "event" ADD CONSTRAINT "UQ_b535fbe8ec6d832dde22065ebdb" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "event" ALTER COLUMN "description" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event" ALTER COLUMN "name" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "points_events" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "points_events" ADD "userId" text`);
        await queryRunner.query(`ALTER TABLE "user_admin_entity" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "user_admin_entity" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "events_points_site" DROP COLUMN "pointsEventsId"`);
        await queryRunner.query(`ALTER TABLE "events_points_site" DROP COLUMN "registration_state"`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "registration_state"`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "pointsMovementId"`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "pointsEventsId"`);
        await queryRunner.query(`ALTER TABLE "site" DROP CONSTRAINT "UQ_6a4f2c06ad82432494fc37fe6a5"`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "idPointValue"`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "updateAt"`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "createAt"`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "site" DROP CONSTRAINT "UQ_cfeaa7e14361e11b3fdfd9fc69f"`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "url"`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "pointsEventsId"`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "create_at"`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "porcentual_value"`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "event_repeats"`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "points"`);
        await queryRunner.query(`ALTER TABLE "points_events" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "site" ADD "pointsMovementId" integer`);
        await queryRunner.query(`ALTER TABLE "site" ADD "pointsEventsId" integer`);
        await queryRunner.query(`ALTER TABLE "site" ADD "idPointValue" integer`);
        await queryRunner.query(`ALTER TABLE "site" ADD CONSTRAINT "UQ_6a4f2c06ad82432494fc37fe6a5" UNIQUE ("idPointValue")`);
        await queryRunner.query(`ALTER TABLE "site" ADD "updateAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "site" ADD "createAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "site" ADD "isActive" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "site" ADD "url" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "site" ADD CONSTRAINT "UQ_cfeaa7e14361e11b3fdfd9fc69f" UNIQUE ("url")`);
        await queryRunner.query(`ALTER TABLE "events_points_site" ADD "registration_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "event" ADD "points" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "event" ADD "porcentual_value" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "event" ADD "event_repeats" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "event" ADD "pointsEventsId" integer`);
        await queryRunner.query(`ALTER TABLE "event" ADD "create_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "site" ADD CONSTRAINT "FK_ab02518d0430b2172bd88ac1e63" FOREIGN KEY ("pointsMovementId") REFERENCES "points_movement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "site" ADD CONSTRAINT "FK_6a4f2c06ad82432494fc37fe6a5" FOREIGN KEY ("idPointValue") REFERENCES "point_value"("id_point_value") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "site" ADD CONSTRAINT "FK_46ba93fc73b6e2d11638400c165" FOREIGN KEY ("pointsEventsId") REFERENCES "points_events"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events_points_site" ADD CONSTRAINT "FK_events_points_site_id_site" FOREIGN KEY ("siteIdSite") REFERENCES "site"("idSite") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events_points_site" ADD CONSTRAINT "FK_events_points_site_event_id" FOREIGN KEY ("eventIdEvent") REFERENCES "event"("id_event") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "points_events" ADD CONSTRAINT "FK_80b087bd8d6927fc9be6ba734bb" FOREIGN KEY ("siteIdSite") REFERENCES "site"("idSite") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event" ADD CONSTRAINT "FK_2671ad705325336d3ae1be4ea60" FOREIGN KEY ("pointsEventsId") REFERENCES "points_events"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "points_events" ADD CONSTRAINT "FK_points_event_events_sites" FOREIGN KEY ("eventIdEvent") REFERENCES "events_points_site"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
